pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: '40b1d2f3-0de0-4ada-b980-70f66ec62084', url: 'https://github.com/KeyboardWarrior26/alx-backend-python.git'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                python3 -m venv ${VENV_DIR}
                source ${VENV_DIR}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                source ${VENV_DIR}/bin/activate
                pytest messaging_app --junitxml=messaging_app/test-results.xml
                '''
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'messaging_app/test-results.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'messaging_app/test-results.xml', allowEmptyArchive: true
            cleanWs()
        }
    }
}

