name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: messaging
          MYSQL_USER: alxuser
          MYSQL_PASSWORD: password123
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MYSQL_DATABASE: messaging
      MYSQL_USER: alxuser
      MYSQL_PASSWORD: password123
      MYSQL_HOST: 127.0.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" --silent; do
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Run Django Migrations
        run: |
          python manage.py migrate

      - name: Run Tests and Generate Coverage Report
        run: |
          coverage run manage.py test
          coverage xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      - name: Run flake8 for linting
        run: |
          flake8 .

