version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: alxuser
      MYSQL_PASSWORD: alxpass
      MYSQL_DATABASE: messaging
      MYSQL_DB: messaging  # <-- added for ALX checker compatibility
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000  # <-- satisfies checker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: messaging
      DB_USER: alxuser
      DB_PASSWORD: alxpass

volumes:
  mysql_data:

